/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_lqtian_ffmpegopencvtest_Util */

#ifndef _Included_com_android_lqtian_ffmpegopencvtest_Util
#define _Included_com_android_lqtian_ffmpegopencvtest_Util

#include "ffmpegdecode.h"

#ifdef __cplusplus
extern "C" {    //必须加入extern "C"才能成功，暂时未知为何
#endif

/*
 * Class:     com_android_lqtian_ffmpegopencvtest_Util
 * Method:    decodeToMat
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jlong JNICALL Java_com_android_lqtian_ffmpegopencvtest_Util_decodeToMat  (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
